language: go

go:
  - 1.13.x

before_install:
  - go mod download

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: VWn+vXFA4PfwOvPxwhsfixZUzy8FDpp9IbR+DTojj4iKVbucP3dO9A3ebRomHmLOBZ46EpgcwHZMY3z6kouTS/l2iyFh7vq71sJEuCMWKnGkx4QN+a1iC9jER4iR+C+8o9M2zY5JGbvnHLmuPAN4PEAgePBAqGKSk9hb0AszQqqrBFWXfXClYY5w150JEztrhu8dzucWmzbU1Exmek+RLbmwvLzh/Oo1vZh5Rmxk6JqX3rMj6Sgr52ywwQPLeGaH7ljZiFcduOBbSQg0ewq0Ip3o3f5gESfg+MTCwWR60bPsqnGllCsMPDhM8OzvY1lRn4enJa0hZNk+A5Lv6m7BRg4Hbk+D7kgf/jo9gm+hPMsD0R+IoGUtwPOP0pQLWfJ+Rf6RgTcngzl45lKJMAXP6q161Dh5QqrSEirRnSP09u/7zZJAaMEEayLnrjj8FXWZ1FpBkZaqDpNuByiRo+tQwh9CoEDV0a5tdJowCF7xGcQoW8p3Kp+ECJTqgyw8wRcuYWAqm1gnCA9PZK0SrvtF0oXt4UYVT7aYoUEiSbGcNuQeK3oWeFUN7ocPU+QSbs6NRA3SnYn/1lK3JrQ4nH2vBRN522OuEZAp7rSMUhhHxLjKJzr0Ls7Yox7X1DqFsXJnuNLC3QNduTbH6E08qs0oBVi35au7SJcOkDsErXc5Ogw=
